### ISSUE TITLE
TypeError being thrown

### ISSUE THREAD

**Issue by tomholland** [wildbit/beanstalk-code-snippet-bot#12]
`TypeError: Cannot match against &#39;undefined&#39; or &#39;null&#39;.<br> &nbsp; &nbsp;at getFileContents (/usr/src/app/src/utils.js:101:65)<br> &nbsp; &nbsp;at storage.forEach (/usr/src/app/src/server.js:63:21)<br> &nbsp; &nbsp;at Object.<anonymous> (/usr/src/app/node_modules/node-persist/src/local-storage.js:178:13)<br> &nbsp; &nbsp;at Array.forEach (native)<br> &nbsp; &nbsp;at Object.LocalStorage.forEach (/usr/src/app/node_modules/node-persist/src/local-storage.js:177:28)<br> &nbsp; &nbsp;at Object.nodePersist.forEach (/usr/src/app/node_modules/node-persist/src/node-persist.js:73:29)<br> &nbsp; &nbsp;at app.route.get.post (/usr/src/app/src/server.js:57:21)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at /usr/src/app/node_modules/body-parser/lib/read.js:129:5`

(the bot is being hosted on beepboop)

**Comment by okonet** [comment]
Where are you seeing this error and what did you do to get it?

**Comment by tomholland** [comment]
When I type

`/code <beanstalk file url>`

in a Slack channel the bot is added to, that is what the bot says back.

To get the URL, I'm clicking on a line of code in the web UI and copying the resulting URL:

`https://<subdomain>.beanstalkapp.com/<repo_name>/browse/trunk/file.ext?ref=c-<revision-no>`

I've tried clicking on the line number instead, so it appends

`#L<[0-9]+>`

to the end of the URL - but I get the same result.

This is based on what the bot responds with when I asked it for 'help':

> _How to get started_
> 1. Browse to a specific file in one of your Beanstalk repositories 
> 2. In Beanstalk, click on the line of code you want to share 
> 3. Copy the URL from your browser and paste it into slack 

Am I just using the wrong URLs? (if so - maybe the bot could check for that, and tell me what I should be doing instead?)

**Comment by okonet** [comment]
I was able to fix the issue but may I know the URL you're using instead of `<beanstalk file url>` so I can add some more tests to the code?

**Comment by okonet** [comment]
The bug fix should be up and running. Can you please check if it solves it?

**Comment by tomholland** [comment]
All I get now is "We had an issue getting the snippet from Beanstalk. Please make sure that you entered the correct username and authorization token." instead of the error output.

Just to confirm a few things.

In the Beep Boop config screen, it asks for Beanstalk username and "Auth Token" - but I'm using API Access tokens, that I'm creating in my account; is that not correct? Does the app not verify these credentials before first trying to use them? (i.e. on save?)

The other part that is somewhat strange is that Beanstalk usernames are only unique within account subdomains(?); does the token mean there is need to account for this?

Can you give an example of the file URL format the app is expecting?

And has this been tested with Subversion as well as Git repositories, btw?

**Comment by okonet** [comment]
1. Yes, "Auth token" is the API token. We recommend creating a special "bot" user in your account and give that user read-only access. Then generate an API token for this user and use it in the BeepBoop screen.
2. We don't validate the credentials at the moment. That's a good point and we will probably will add it. I'll add a separate issue for it.
3. Yes, you'll need a user/token for each of your accounts. I'm not sure you can add several bots to your Slack team. At the moment our Bot supports only one Beanstalk per bot and if this is a case, we might want to extend it as well.
4. The bot expects an URL you'll see when browsing files (/browse). Something like this: `https://<account>.beanstalkapp.com/<repository>]/browse/git/<filename>`
5. We don't use Subversion anymore but it should work as well since the bot is using the API that's VCS independent AFAIK.

**Comment by tomholland** [comment]
Ok - figured it out: I don't get the credentials error when I try and reference a file in a Git repository - only Subversion repositories. Beanstalk still offer both (I prefer Git, but still have to work with Subversion ones sometimes).

If it needs special attention to work with Subversion (and it's not something you want to look into, because you don't use Subversion repositories any more), it might be worth highlighting it's Git repositories only in the README.md file / help docs (saves other Subversion users the time figuring that out / pestering you with duplicate issues).

You might be able to detect if it's not a Git repo and give a Subversion unsupported warning? My Git repo file URLs seem to start with this:

`https://<subdomain>.beanstalkapp.com/<repo_name>/browse/git/`

(my project doesn't have a 'git' directory at root level! - so I presume this is something generic on Beanstalk's side)

…whereas, my Subversion URLs start like like this:

`https://<subdomain>.beanstalkapp.com/<repo_name>/browse/trunk
https://<subdomain>.beanstalkapp.com/<repo_name>/browse/tags
https://<subdomain>.beanstalkapp.com/<repo_name>/browse/branches`

(I don't think you could rely on solely on 'trunk', 'tags' or 'branches' being the only ones that might be present for a Subversion repository - since I believe they are just directories, so you could add your own at the root level [although it's not the standard approach]; however, maybe the 3rd [index 2] path component not being 'git' would be a good indicator that it's a Subversion repo - and the bot can give a specific response about not reporting Subversion repositories?)

**Comment by tomholland** [comment]
Oh, and I know it's minor; but on your item 1 - it is possible to amend the label from "Auth token" to "API Access token" in the Beep Boop config screen? I'd assumed that was what it meant - but the terminology is different enough (especially if you've worked with OAuth before) to make one wonder if you are using the right kind of credential ;) (especially if the bot is responding saying "Please make sure that you entered the correct username and authorization token"; I did review the Beanstalk API docs, to make sure I wasn't missing something about different credential types...)

**Comment by okonet** [comment]
Very good points!

We'll look into subversion issues soon. I've created separate issues for these.

See #15, #16
